name: Java CI with Gradle and AWS CodeDeploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle (Skip Tests)
        run: ./gradlew build -x test

      - name: Create Deployment Directory (before-deploy)
        run: mkdir -p before-deploy

      - name: Copy Deployment Files
        run: |
          cp scripts/*.sh before-deploy/  # 실행 스크립트 복사
          cp appspec.yml before-deploy/  # AWS CodeDeploy 설정 파일 복사
          cp build/libs/*.jar before-deploy/  # Gradle 빌드된 JAR 파일 복사

      - name: Zip Deployment Package
        run: |
          cd before-deploy && zip -r before-deploy.zip *  # ZIP 생성
          cd ../ && mkdir -p deploy  # deploy 폴더 생성
          mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip  # ZIP 이동

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp deploy/freelec-springboot2-webservice.zip s3://freelec-springboot-book --acl private

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name freelec-springboot-webservice \
            --deployment-group-name freelec-springboot-webservice-group \
            --s3-location bucket=freelec-springboot-book,key=freelec-springboot2-webservice.zip,bundleType=zip \
            --region ap-northeast-2
